management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always

info:
  app:
    name: "Cinema Spring Boot App"
    description: "The Cinema system is an Internet showcase of a cinema with one hall."
    version: 2.0.0
